package com.example.tugaspraktikum3;

import java.util.ArrayList;

public class DataSource {

    public static ArrayList<Post>posts=generateDummyPost();

    private static ArrayList<Post> generateDummyPost() {
        ArrayList<Post> posts= new ArrayList<>();
        posts.add(new Post(R.drawable.alfaromeolog,R.drawable.alfaromeopost,"alfaromeo","Alfa Romeo Racing Orlen adalah tim balap Formula 1 berbasis di Hinwil, Swiss, dengan sponsor utama PKN Orlen. Tim ini mewakili warisan Alfa Romeo dalam balap mobil. Meskipun tidak selalu di puncak, mereka tetap menjadi peserta konsisten dengan fokus pada pengembangan mobil dan pembalap.",R.drawable.alfaromeostory,100,2));
        posts.add(new Post(R.drawable.scuderia,R.drawable.cl,"scuderiaferrari","Ferrari adalah tim balap Formula 1 terkenal asal Italia. Berbasis di Maranello, mereka memiliki warisan yang kaya dengan lebih dari 200 kemenangan Grand Prix dan lebih dari 15 gelar juara dunia. Lambang kuda jantan hitam di latar belakang merah menjadi ikonik bagi tim ini.",R.drawable.ferraristory,800,1));
        posts.add(new Post(R.drawable.alphataurilog,R.drawable.alphatauripost,"f1alphatauri","AlphaTauri adalah tim balap Formula 1 Italia, dulunya dikenal sebagai Toro Rosso. Sebagai saudara dari Red Bull Racing, mereka berbasis di Faenza, Italia. AlphaTauri fokus pada pengembangan bakat baru dan sering menampilkan gaya balap agresif di lintasan.",R.drawable.alphatauristory,200,0));
        posts.add(new Post(R.drawable.rbhondalog,R.drawable.rbhondapost,"redbullracing","Red Bull Racing adalah tim balap Formula 1 yang sukses dan agresif. Didirikan pada tahun 2004, mereka merupakan bagian dari Red Bull GmbH dan berbasis di Milton Keynes, Inggris. Tim ini dikenal karena gaya balapnya yang agresif dan telah meraih banyak kemenangan dan gelar juara dunia dalam olahraga ini.",R.drawable.rbracingstory,300,1));
        posts.add(new Post(R.drawable.marcedeslog,R.drawable.marcedespost,"marcedesamgf1","Mercedes-AMG Petronas Formula One Team adalah tim balap Formula 1 yang dominan. Didirikan pada tahun 2010, mereka telah menjadi kekuatan utama dalam olahraga ini. Berbasis di Brackley, Inggris, dan dipimpin oleh Toto Wolff, Mercedes telah memenangkan banyak gelar juara dunia konstruktor dan pembalap, dengan Lewis Hamilton sebagai salah satu pembalapnya yang paling sukses.",R.drawable.marcedesstory,200,3));
        posts.add(new Post(R.drawable.mclarenlogo,R.drawable.mclarenpost,"mclaren","McLaren adalah tim balap Formula 1 yang bersejarah. Didirikan pada tahun 1963 oleh Bruce McLaren, mereka telah menjadi salah satu kekuatan utama dalam olahraga ini. Berbasis di Woking, Inggris, McLaren dikenal karena inovasi teknis dan sejarah kesuksesannya. Mereka telah meraih banyak gelar juara dunia konstruktor dan pembalap, dengan pembalap-pembalap seperti Ayrton Senna dan Lewis Hamilton yang membantu membangun reputasi tim ini.",R.drawable.mclarenstory,100,1));
        posts.add(new Post(R.drawable.astonmartinlog,R.drawable.astonmartinpost,"astonmartinf1","Aston Martin adalah merek mobil mewah asal Inggris yang terkenal di seluruh dunia. Mereka juga memiliki tim balap Formula 1 yang berkompetisi dengan nama Aston Martin Cognizant Formula One Team. Tim ini berbasis di Silverstone, Inggris, dan menjadi bagian dari kebangkitan merek Aston Martin dalam dunia otomotif balap. Sebelumnya dikenal sebagai Racing Point, tim ini telah menjadi pesaing yang solid di grid Formula 1.",R.drawable.astonmartinstory,500,2));
        posts.add(new Post(R.drawable.alpinelog,R.drawable.alpinepost,"alpinef1team","Alpine adalah tim balap Formula 1 yang berbasis di Enstone, Inggris, sebelumnya dikenal sebagai tim Renault. Mereka merupakan bagian dari Grup Renault dan menjadi tim pabrikan dari merek mobil sport Prancis, Alpine. Tim ini memiliki sejarah yang kaya dalam olahraga balap dan telah meraih banyak kesuksesan di berbagai ajang balap, termasuk Formula 1. Dengan pembalap-pembalap seperti Fernando Alonso, Alpine bertujuan untuk menjadi pesaing yang kuat di grid balap Formula 1.",R.drawable.alpinestory,300,1));
        posts.add(new Post(R.drawable.haaslog,R.drawable.haaspost,"haaasf1team","Haas F1 Team adalah tim balap Formula 1 yang berbasis di Kannapolis, North Carolina, Amerika Serikat. Didirikan pada tahun 2014 oleh Gene Haas, pendiri perusahaan manufaktur Haas Automation, tim ini menjadi wakil Amerika Serikat di kejuaraan dunia Formula 1. Mereka menggunakan mesin yang dipasok oleh Ferrari dan telah berkompetisi di grid Formula 1 sejak musim 2016. Haas F1 Team dikenal karena pendekatannya yang pragmatis terhadap bisnis balap dan telah memberikan kesempatan bagi pembalap muda untuk berkembang dalam olahraga ini.",R.drawable.haasstory,400,1));
        return posts;
    }
}
